### ISSUE TITLE
Program is not portable

### ISSUE THREAD

**Issue by Sharpthy** [MatthewKing/SkypeQuoteCreator#3]
This program needs to be installed to run. For such a small program, filling a rather niche purpose, perhaps it is better to have it as a single launchable executable.

**Comment by jkmartindale** [comment]
Yes, this would be nice.

**Comment by MatthewKing** [comment]
Thanks for the feedback. This is a good idea.

I'll provide the option to download the software as a stand-alone executable.

I'm going to keep the ClickOnce installer as the 'recommended' option, though; a lot of users find the installation and auto-update features useful.

**Comment by MatthewKing** [comment]
I've now added an option to download the software as a stand-alone executable.
