### ISSUE TITLE
This doesn't work anymore, right?

### ISSUE THREAD

**Issue by ErnestUTN** [MatthewKing/SkypeQuoteCreator#5]
Using Skype Versión 8.37.0.98

**Comment by MatthewKing** [comment]
You're right, it looks like it doesn't work any more.

I don't like the direction that Skype have taken their product in, so I'm no longer an active user. I'm not even sure it's possible to copy+paste "quotes" in the new versions.

**Comment by ErnestUTN** [comment]
Yeah. You can't even do that.. I just try to format the  text to look like  that with " ``` "
